import type { GraphiteTheme } from "@/components/charts/graphite/Chart";

/**
 * Generated by Graphite, tuned to Dockhand's tokens (surfaces match --surface,
 * tracks match --line-1). Import once; pass to every chart.
 */
export const graphiteTheme = {
  defaultMode: "auto",
  surface: "transparent",
  modes: {
    light: {
      background: "#eef0f5",
      surface: "#ffffff",
      border: "rgba(0,0,0,.06)",
      text: "#171a21",
      muted: "#7a8190",
      grid: "rgba(0,0,0,.06)",
      track: "rgba(0,0,0,.06)",
    },
    dark: {
      background: "#0d1016",
      surface: "#1a1f2a",
      border: "rgba(255,255,255,.07)",
      text: "#e9ecf3",
      muted: "#7d8596",
      grid: "rgba(255,255,255,.07)",
      track: "rgba(255,255,255,.07)",
    },
  },
  palette: ["#2f6fed", "#7a5cf0", "#22a06b", "#e0a020"],
  font: "JetBrains Mono",
  radius: 0,
  stroke: 2.5,
  fill: 0.4,
  curve: "smooth",
  grid: false,
  legend: false,
  labels: false,
} as const satisfies GraphiteTheme;

export type SeriesColor = (typeof graphiteTheme.palette)[number];
